CREATE TABLE IF NOT EXISTS devices (
 ID INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 device_name VARCHAR(200) NOT NULL,
 config VARCHAR(2000) NOT NULL,
 experation_date DATE NOT NULL,
 CONSTRAINT `fk_user_devices` FOREIGN KEY (`user_id`) REFERENCES `users` (`ID`) ON DELETE CASCADE
);
 
CREATE TABLE IF NOT EXISTS users (
 ID INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(200) UNIQUE NOT NULL,
 user_pass VARCHAR(64) NOT NULL
);

INSERT INTO users (username, user_pass) VALUES ('test', '02B8188DB90C04CCFC28FE217C8BB0CFFD80BBB76119A76CC2AC276D9F96EC59');